#this targets the master branch of hte wired in GitHub repo. IT watches for any action against master
trigger:
  - 'master'

#targets any PR on any branch in the repo. highly recommended to put this in to control which
pr: 'none'

#stages allow the sME SERIES OF ACTIONS TO BE REPOICATED ON MULTIPLE ENVIRONMENTS.
stages:
  - stage:
    #a job is the smallest unit that can run in a pipeline
    #Job is the "unit of work"" that gets schedules on the machine. 
    #divide the scripts into different jobs.
    jobs:  
      - job: 'build'
        #what CLI command to use
        steps:
          - script: 'dotnet build'

  - stage:
    jobs:
      job: 'test'
        dependsOn: 'build'
        steps:
          - script: 'dotnet test'

      job: 'publish'
        dependsOn: 'test'
        steps:
          - script: 'dotnet publish'


#this gives the whole build a lname.
name: '$(date:yyyyMMdd)$(rev:.rr)'